name: user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  async: ^2.8.1
  badges: ^2.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  convex_bottom_bar: ^3.0.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: 3.0.1
  firebase_core: 1.4.0
  firebase_messaging: 10.0.4
  flat_segmented_control: ^0.1.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  flutter_bloc: ^7.3.0
  flutter_credit_card: ^3.0.0
  flutter_facebook_login: ^3.0.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_google_places: ^0.3.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_image_slideshow: ^0.1.2
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_paystack: ^1.0.5
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_share: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_speed_dial: ^4.4.0+1
  flutter_svg: ^0.21.0
  geocoder: ^0.2.1
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.10
  google_place: ^0.4.0
  google_sign_in: ^5.1.1
  grouped_buttons: ^1.0.4
  http: ^0.13.1
  http_auth: ^1.0.0
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  mapbox_search: ^3.0.1+1
  marquee: ^2.0.0
  path_provider: ^2.0.5
  paytm_allinonesdk: ^1.1.3
  pdf: ^3.1.0
  percent_indicator: ^3.0.1
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_text_field: ^1.8.0
  pinput: ^1.2.0
  printing: ^5.0.4
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.2.5
  shared_preferences: ^2.0.8
  shimmer_animation: ^2.0.0
  sign_in_with_apple: ^3.1.0
  slide_drawer: ^1.0.3
  sliding_up_panel: ^2.0.0+1
  timelines: ^0.1.0
  toast: ^0.1.5
  tree_view: ^0.0.5
  url_launcher: ^6.0.12
#  internet_connection_checker: ^0.0.1+1
dev_dependencies:
  change_app_package_name: ^1.0.0
  #  json_serializable: ^3.4.1
  #  intl_translation: ^0.17.9
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf

  assets:
    - assets/
    - assets/ProductImages/
    - assets/PaymentIcons/
    - assets/CategoryImages/
    - assets/Subscribe/
    - assets/HomeBanner/
    - assets/IntroScreen/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf
